# Generated by Django 4.1.7 on 2023-03-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('us_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('us_name', models.CharField(max_length=100)),
                ('us_email', models.CharField(max_length=100)),
                ('us_mobile', models.CharField(max_length=20)),
                ('us_password', models.CharField(max_length=30)),
            ],
        ),
    ]
