# Generated by Django 4.1.7 on 2023-04-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ad_email_id', models.CharField(max_length=100)),
                ('ad_password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('ar_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ar_city', models.CharField(max_length=100)),
                ('ar_area', models.CharField(max_length=30)),
                ('ar_latitude', models.CharField(max_length=30)),
                ('ar_longitude', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('bl_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('bl_balance', models.CharField(max_length=100)),
                ('bl_created_by', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('ct_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ct_places', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('dt_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('dt_city', models.CharField(max_length=100)),
                ('dt_from', models.CharField(max_length=30)),
                ('dt_to', models.CharField(max_length=30)),
                ('dt_distance', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('st_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('st_state', models.CharField(max_length=100)),
                ('st_city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usercategory',
            fields=[
                ('uc_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('uc_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usertransactions',
            fields=[
                ('ut_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ut_transactions', models.CharField(default='null', max_length=100)),
                ('ut_category', models.CharField(max_length=100)),
                ('ut_amount', models.CharField(max_length=100)),
                ('ut_debit_or_credit', models.CharField(max_length=20)),
                ('ut_date', models.CharField(max_length=30)),
                ('ut_created_by', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='users',
            old_name='us_email',
            new_name='us_email_id',
        ),
    ]
