# Generated by Django 4.1.7 on 2023-04-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_admin_area_balance_city_distance_state_usercategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='ar_link',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
