# Generated by Django 4.1.7 on 2023-04-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_area_ar_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='ar_link',
            field=models.TextField(default='null'),
        ),
    ]
