# Generated by Django 4.1.7 on 2023-04-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_area_ar_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('lc_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('lc_city', models.CharField(max_length=100)),
                ('lc_area', models.CharField(max_length=30)),
                ('lc_category', models.CharField(max_length=30)),
                ('lc_name', models.CharField(max_length=30)),
                ('lc_description', models.TextField()),
                ('lc_image', models.CharField(max_length=30)),
                ('lc_link', models.TextField()),
            ],
        ),
    ]
