# Generated by Django 4.1.7 on 2023-04-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lc_image',
            field=models.ImageField(upload_to='app/static/admin_img/'),
        ),
    ]
