# Generated by Django 4.1.7 on 2023-04-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_location_lc_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('ur_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ur_mobile', models.CharField(max_length=20)),
                ('ur_password', models.CharField(max_length=30)),
            ],
        ),
    ]
