# Generated by Django 4.1.7 on 2023-05-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_admin_ad_mobile_admin_ad_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='uc_image',
            field=models.ImageField(default='null', upload_to='app/static/user_img/'),
        ),
    ]
