# Generated by Django 4.1.7 on 2023-05-04 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_users_uc_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='uc_image',
            new_name='us_image',
        ),
    ]
