# Generated by Django 4.1.7 on 2023-05-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_uc_image_users_us_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('fd_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fd_name', models.CharField(max_length=100)),
                ('fd_email', models.CharField(max_length=30)),
                ('fd_feedback', models.TextField()),
            ],
        ),
    ]
